version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: /Frontend/frontend/Dockerfile
    volumes:
      - ./Frontend/frontend/:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: /Backend/Dockerfile
    ports:
      - "8801:8801"
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=zuheb101625
      - DB_NAME=signup

  database:
    image: mariadb:10.4.32
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: zuheb101625
      MYSQL_DATABASE: signup
    volumes:
      - ./data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci

volumes:
  data:
