version: "3.8"
services:
  frontend:
    image: zuheb8809/frontend:1.0
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: zuheb8809/backend:1.0
    ports:
      - "8801:8801"
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=zuheb101625
      - DB_NAME=signup

  database:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: zuheb101625
      MYSQL_DATABASE: signup
    volumes:
      - ./data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci

volumes:
  data:
